### ISSUE TITLE
Filter out restricted works from downstream processing

### ISSUE THREAD

**Issue by TBRC-JimK** [buda-base/archive-ops#57]
Find out how to access TBRC or BUDA API to get restrictions on works, unless we get them from the MARC record already.
Once that's done, use that to divert works from IA processing.

**Comment by TBRC-Travis** [comment]
The restriction type for each work is already captured in the XML metadata that gets sent to IA.  **We shouldn't be diverting works based on restriction type.**  Rather we should continue doing what we've been doing -- send everything up to IA and let them handle the work accordingly. 
 IA is already handling the access field designations as we've specified them.  This how the various access levels are handled on their site:

“fairUse” - borrowable, no downloads
“restrictedSealed” - no access
“temporarilyRestricted” - no access
“restrictedByQuality” - no access
“restrictedByTbrc” - no access
“restrictedInChina” - not downloadable or borrowable by IP addresses in China, streaming only for everywhere else.

Thus, Internet Archive receives everything in our archive, but restricted works are not available on their site for public viewing.

**Comment by TBRC-pmench** [comment]
Is metadata viewable for restricted materials on IA or is it just in their system but totally hidden from the public? For embargoed materials, we shouldn't have the records be accessible at all, I think.

**Comment by TBRC-Travis** [comment]
I'd have to do some more extensive searching to verify for sure, but I believe for restricted material it is searchable and the metadata is viewable, but nothing else.  The exception to that is RestrictedInChina material which simply doesn't show up on Internet Archive right now (from what I recall, the reason for this is because they hadn't yet implemented the appropriate geo restrictions).  I presume what you refer to as "embargoed" would be equivalent to our Restricted in China texts?

Regardless, I don't really see a problem with the metadata being available on archive.org since it's already accessible and viewable on our own site as well.  Google's search index already has access to all the metadata on our site anyway.
